# Generated by Django 6.0 on 2025-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('identificador', models.IntegerField(unique=True)),
                ('fecha_de_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
