# Generated by Django 6.0 on 2025-12-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anillos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.IntegerField(unique=True)),
                ('unidades', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha_de_actualizacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aretes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.IntegerField(unique=True)),
                ('unidades', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha_de_actualizacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caballeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.IntegerField(unique=True)),
                ('unidades', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha_de_actualizacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.IntegerField(unique=True)),
                ('unidades', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha_de_actualizacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Combinados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.IntegerField(unique=True)),
                ('unidades', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha_de_actualizacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pulseras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.IntegerField(unique=True)),
                ('unidades', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha_de_actualizacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
